from src.domain.errors.models.base_error_code import BaseErrorCode


class InternalErrorCodes(BaseErrorCode):
    SEND_EMAIL_CREATE_AUTH_CODE_ERROR = (500300, "Send email to create auth code error")
    CANNOT_PERSIST_EMAIL_CODE_ERROR = (500301, "Cannot persist email code error")
    VALIDATE_EMAIL_CODE_INTERNAL_ERROR = (500302, "Validate email code internal error")
    CREATE_AUTH_ERROR = (500303, "Create auth internal error")
    LOGIN_INTERNAL_ERROR = (500304, "Login internal error")
    RESET_PASSWORD_ERROR = (500305, "Reset password internal error")
    SEND_EMAIL_FORGET_PASSWORD_CODE_ERROR = (500306, "Send email to forget password code error")
    SEND_EMAIL_VERIFICATION_CODE_ERROR = (500307, "Send email to verification code error")
    UPDATE_PASSWORD_ERROR = (500308, "Update password internal error")
    CREATE_CURRENT_USER_ERROR = (500309, "Create current user internal error")
    GET_CURRENT_USER_ERROR = (500310, "Get current user internal error")
    UPDATE_CURRENT_USER_ERROR = (500312, "Update current user internal error")
    GET_USER_FAMILY_ERROR = (500313, "Get user family internal error")
    CREATE_CHORE_ERROR = (500314, "Chore operation error")
    UPDATE_CHORE_ERROR = (500315, "Update chore operation error")
    DELETE_CHORE_ERROR = (500316, "Delete chore operation error")
    GET_CHORE_ERROR = (500317, "Get chore operation error")
    LIST_CHORES_ERROR = (500318, "Get chores operation error")
    CREATE_FAMILY_MEMBER_ERROR = (500319, "Create family member operation error")
    GET_FAMILY_MEMBER_ERROR = (500320, "Get family members operation error")
    UPDATE_FAMILY_MEMBER_ERROR = (500321, "Update family member operation error")
    DELETE_FAMILY_MEMBER_ERROR = (500322, "Delete family member operation error")
    LIST_FAMILY_MEMBERS_ERROR = (500323, "List family members error")
    RESEND_FAMILY_MEMBER_PASSWORD_ERROR = (500324, "Resend family member password error")
    REFRESH_TOKEN_ERROR = (500325, "Refresh token internal error")
    GENERATE_REFRESH_TOKEN_ERROR = (500326, "Generate refresh token internal error")
    ASSIGN_CHORE_TO_ME_ERROR = (500327, "Assign chore to me operation error")
    REMOVE_ASSIGN_CHORE_TO_ME_ERROR = (500328, "Remove assign chore to me operation error")
    COMPLETE_CHORE_ERROR = (500329, "Complete chore operation error")
    LIST_DAYS_OF_WEEK_ERROR = (500330, "List days of week operation error")
